unit TestufTarefa2;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, Vcl.Dialogs, Winapi.Windows, System.SysUtils, Vcl.ComCtrls,
  Vcl.Graphics, System.Variants, ufTarefa2, Winapi.Messages, Vcl.StdCtrls, Vcl.Controls,
  Vcl.Forms, System.Classes;

type
  // Test methods for class TfTarefa2

  TestTfTarefa2 = class(TTestCase)
  strict private
    FfTarefa2: TfTarefa2;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestButton1Click;
    procedure TestFormClose;
  end;
  // Test methods for class TThread1

  TestTThread1 = class(TTestCase)
  strict private
    FThread1: TThread1;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  end;
  // Test methods for class TThread2

  TestTThread2 = class(TTestCase)
  strict private
    FThread2: TThread2;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  end;

implementation

procedure TestTfTarefa2.SetUp;
begin
  FfTarefa2 := TfTarefa2.Create(nil);
end;

procedure TestTfTarefa2.TearDown;
begin
  FfTarefa2.Free;
  FfTarefa2 := nil;
end;

procedure TestTfTarefa2.TestButton1Click;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FfTarefa2.Button1Click(Sender);
  // TODO: Validate method results
end;

procedure TestTfTarefa2.TestFormClose;
var
  Action: TCloseAction;
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FfTarefa2.FormClose(Sender, Action);
  // TODO: Validate method results
end;

procedure TestTThread1.SetUp;
begin
  FThread1 := TThread1.Create;
end;

procedure TestTThread1.TearDown;
begin
  FThread1.Free;
  FThread1 := nil;
end;

procedure TestTThread2.SetUp;
begin
  FThread2 := TThread2.Create;
end;

procedure TestTThread2.TearDown;
begin
  FThread2.Free;
  FThread2 := nil;
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTfTarefa2.Suite);
  RegisterTest(TestTThread1.Suite);
  RegisterTest(TestTThread2.Suite);
end.

