unit TestuPrincipal;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, Vcl.Dialogs, Winapi.Windows, System.SysUtils, System.Variants,
  Vcl.Graphics, Vcl.Menus, Winapi.Messages, Vcl.Controls, Vcl.Forms,
  System.Classes, uPrincipal;

type
  // Test methods for class TPrincipal

  TestTPrincipal = class(TTestCase)
  strict private
    FPrincipal: TPrincipal;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestTarefa1Click;
    procedure TestTarefa2Click;
    procedure TestTarefa3Click;
  end;

implementation

procedure TestTPrincipal.SetUp;
begin
  FPrincipal := TPrincipal.Create(nil);
end;

procedure TestTPrincipal.TearDown;
begin
  FPrincipal.Free;
  FPrincipal := nil;
end;

procedure TestTPrincipal.TestTarefa1Click;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FPrincipal.Tarefa1Click(Sender);
  // TODO: Validate method results
end;

procedure TestTPrincipal.TestTarefa2Click;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FPrincipal.Tarefa2Click(Sender);
  // TODO: Validate method results
end;

procedure TestTPrincipal.TestTarefa3Click;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FPrincipal.Tarefa3Click(Sender);
  // TODO: Validate method results
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTPrincipal.Suite);
end.

