unit TestufTarefa3;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, Vcl.Dialogs, Winapi.Windows, Vcl.StdCtrls, System.SysUtils, ufTarefa3,
  Vcl.Graphics, System.Variants, Vcl.Grids, Vcl.DBGrids, Winapi.Messages,
  Datasnap.DBClient, Vcl.Controls, Vcl.Forms, Data.DB, System.Classes;

type
  // Test methods for class TfTarefa3

  TestTfTarefa3 = class(TTestCase)
  strict private
    FfTarefa3: TfTarefa3;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestFormCreate;
    procedure TestFormClose;
    procedure TestButton1Click;
    procedure TestButton2Click;
  end;

implementation

procedure TestTfTarefa3.SetUp;
begin
  FfTarefa3 := TfTarefa3.Create(nil);
end;

procedure TestTfTarefa3.TearDown;
begin
  FfTarefa3.Free;
  FfTarefa3 := nil;
end;

procedure TestTfTarefa3.TestFormCreate;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FfTarefa3.FormCreate(Sender);
  // TODO: Validate method results
end;

procedure TestTfTarefa3.TestFormClose;
var
  Action: TCloseAction;
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FfTarefa3.FormClose(Sender, Action);
  // TODO: Validate method results
end;

procedure TestTfTarefa3.TestButton1Click;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FfTarefa3.Button1Click(Sender);
  // TODO: Validate method results
end;

procedure TestTfTarefa3.TestButton2Click;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FfTarefa3.Button2Click(Sender);
  // TODO: Validate method results
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTfTarefa3.Suite);
end.

