unit TestufTarefa1;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, Vcl.Dialogs, Winapi.Windows, ufTarefa1, System.SysUtils, Vcl.Graphics,
  System.Variants, Winapi.Messages, Vcl.StdCtrls, Vcl.Controls, Vcl.Forms,
  System.Classes;

type
  // Test methods for class TfTarefa1

  TestTfTarefa1 = class(TTestCase)
  strict private
    FfTarefa1: TfTarefa1;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestButton1Click;
  end;

implementation

procedure TestTfTarefa1.SetUp;
begin
  FfTarefa1 := TfTarefa1.Create(nil);
end;

procedure TestTfTarefa1.TearDown;
begin
  FfTarefa1.Free;
  FfTarefa1 := nil;
end;

procedure TestTfTarefa1.TestButton1Click;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FfTarefa1.Button1Click(Sender);
  // TODO: Validate method results
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTfTarefa1.Suite);
end.

